name: Clean expired subscriptions

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  clean_expired:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run script
        run: python3 scripts/remove_expired.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Auto remove expired subscriptions"
          git push
